### ISSUE TITLE
Einen Plan hinzufügen ohne das Feld zu füllen fügt den als letztes hinzugefügten Plan nochmal hinzu

### ISSUE THREAD

**Issue by mm-juliangiebel** [1liqm/Gym#1]
![Screenshot 2024-02-29 at 10-25-33 Motion Media kreativ am Heger Tor - Werbeagentur Osnabrück](https://github.com/1liqm/Gym/assets/87303610/fbfa3ae0-f30a-4599-bee9-7240cbf4dadc)

**Comment by 1liqm** [comment]
Lieber Herr Giebel,
Ich bedanke mich erstmal für die Rückmeldung und das Reporten des Bugges, ich werde mich schnellstmöglich um dieses Problem kümmern um ihnen eine Höchstmöglich angenehme FitFun Erfahrung bieten zu können.  Ich werde mich mit meinem Lehrer besprechen (der mir das so schlecht gezeigt hat) und werde in den nächsten Tagen ein Bugfix posten.
~1Liqm
